<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="ManageCategory.aspx.cs" Inherits="Page_Product_ManageCategory" Title="مديريت شاخه ها"
    ErrorPage="~/Page/Errors/Error500.htm" MaintainScrollPositionOnPostback="true" %>

<%@ Register Src="~/WebControls/Common/WaitPanel.ascx" TagName="WaitPanel" TagPrefix="wtp" %>
<asp:Content ID="MasterHeadContent" ContentPlaceHolderID="HeadContentPlaceHolder"
    runat="Server">

    <script language="javascript" type="text/javascript">
        function CheckForSelectedNodes()
        {
            checked = false;
            
            var checkBoxes = document.getElementsByTagName("input");
            for (var i = 0; i < checkBoxes.length; i++)
            {
                if (checkBoxes[i].type == "checkbox" && checkBoxes[i].checked)
                {
                    checked = true;
                    break;
                }
            }

            if (!checked)
            {
                alert('.هيچ شاخه اي براي حذف نشانه گذاري نشده است');
                return false;
            }
            else       
                return confirm('آيا واقعا مايل به حذف اين شاخه ها و تمام زيرشاخه ها و محصولات آنها هستيد؟');      
        }
        
        function clickButton(e, buttonid)
        {
            var evt = e? e: window.event;
            var bt = document.getElementById(buttonid);
            if (bt)
            {
                if (evt.keyCode == 13)
                {
                    bt.click();
                    return false;
                }
            }          
        }        
    </script>

</asp:Content>
<asp:Content ID="ManageCategoryContent" ContentPlaceHolderID="MasterContentPlaceHolder"
    runat="Server">
    <div class="masterContent">
        <h3 class="signupTable" style="color: Gray">
            مديريت شاخه ها</h3>
        <hr style="border-top: 1px dashed Gray;" />
        <asp:Panel ID="ManageCategoryPanel" runat="server" DefaultButton="AddButton">
            <asp:UpdatePanel ID="ManageCategoryUpdatePanel" runat="server">
                <ContentTemplate>
                    <asp:Label ID="MovedItemName" runat="server" Font-Names="Tahoma" Font-Bold="true"
                        Visible="false" Font-Size="10pt" ForeColor="#333399"></asp:Label>
                    <br />
                    <table class="signupTable">
                        <tr>
                            <td style="background-color: #99ff99">
                                <asp:TreeView ID="CategoryTreeView" runat="server" DataSourceID="CategorySiteMapDataSource"
                                    ImageSet="Arrows" OnSelectedNodeChanged="CategoryTreeView_SelectedNodeChanged"
                                    ShowCheckBoxes="All" LineImagesFolder="~/Images/TreeLineImages" ShowLines="True"
                                    PopulateNodesFromClient="true" AutoGenerateDataBindings="false">
                                    <RootNodeStyle Font-Bold="True" />
                                    <ParentNodeStyle Font-Bold="False" />
                                    <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
                                    <SelectedNodeStyle Font-Underline="True" ForeColor="#5555DD" HorizontalPadding="0px"
                                        VerticalPadding="0px" />
                                    <NodeStyle Font-Names="Tahoma" Font-Size="10pt" ForeColor="Black" HorizontalPadding="5px"
                                        NodeSpacing="0px" VerticalPadding="0px" />
                                    <DataBindings>
                                        <asp:TreeNodeBinding TextField="Title" ValueField="Key" SelectAction="SelectExpand"
                                            ToolTipField="Description" />
                                    </DataBindings>
                                </asp:TreeView>
                                <asp:SiteMapDataSource ID="CategorySiteMapDataSource" runat="server" />
                            </td>
                            <td>
                                <table>
                                    <tr>
                                        <td style="width: 150px">
                                            <asp:Label ID="DeleteAllLabel" runat="server" Text="حذف تمام شاخه هاي نشانه گذاري شده"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:Button ID="DeleteAllButton" runat="server" Width="50px" Text="حذف" CausesValidation="false"
                                                OnClick="DeleteAllButton_Click" OnClientClick="javascript: return CheckForSelectedNodes();"
                                                ToolTip="حذف تمام شاخه هاي نشانه گذاري شده" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            &nbsp;</td>
                                        <td>
                                            &nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:Label ID="DeleteButtonLabel" runat="server" Text="حذف شاخه انتخاب شده"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:Button ID="DeleteButton" runat="server" Width="50px" Enabled="False" Text="حذف"
                                                ToolTip="حذف شاخه انتخاب شده" OnClientClick="javascript: return confirm('آيا واقعا مايل به حذف اين شاخه و تمام زيرشاخه ها و محصولات آنها هستيد؟');"
                                                OnClick="DeleteButton_Click" CausesValidation="false" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            &nbsp;</td>
                                        <td>
                                            &nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:Label ID="MoveLabel" runat="server" Text="انتقال شاخه انتخاب شده"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:Button ID="MoveButton" runat="server" Width="50px" Enabled="False" Text="انتقال"
                                                ToolTip="انتقال شاخه انتخاب شده" OnClick="MoveButton_Click" CausesValidation="false" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            &nbsp;</td>
                                        <td>
                                            &nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:Label ID="NameLabel" runat="server" Text="تغيير نام شاخه انتخاب شده" AssociatedControlID="NameTextBox"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:TextBox ID="NameTextBox" runat="server" Enabled="False" ToolTip="نام شاخه" ForeColor="Blue"
                                                Font-Italic="true" Width="100px" MaxLength="100">
                                            </asp:TextBox>&nbsp;<asp:RequiredFieldValidator ID="NameRequiredFieldValidator" runat="server"
                                                ErrorMessage="*" ControlToValidate="NameTextBox" ValidationGroup="ManageCatUpdate"></asp:RequiredFieldValidator>
                                            <asp:Button ID="UpdateNameButton" runat="server" Text="تغيير" Width="50px" Enabled="False"
                                                OnClick="UpdateNameButton_Click" ValidationGroup="ManageCatUpdate" ToolTip="تغيير نام شاخه انتخاب شده" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            &nbsp;</td>
                                        <td>
                                            &nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:Label ID="SubCategoryNameLabel" runat="server" Text="اضافه کردن يک زيرشاخه به شاخه انتخاب شده"
                                                AssociatedControlID="SubCategoryNameTextBox"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:TextBox ID="SubCategoryNameTextBox" runat="server" Enabled="False" ToolTip="نام زيرشاخه جديد"
                                                ForeColor="Blue" Font-Italic="true" Width="100px" MaxLength="100">
                                            </asp:TextBox>&nbsp;<asp:RequiredFieldValidator ID="SubCategoryNameRequiredFieldValidator"
                                                runat="server" ErrorMessage="*" ControlToValidate="SubCategoryNameTextBox" ValidationGroup="ManageCatAdd"></asp:RequiredFieldValidator>
                                            <asp:Button ID="AddButton" runat="server" Text="اضافه" Width="50px" Enabled="False"
                                                OnClick="AddButton_Click" ValidationGroup="ManageCatAdd" ToolTip="اضافه کردن يک زيرشاخه به شاخه انتخاب شده" />
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </ContentTemplate>
            </asp:UpdatePanel>
            <asp:UpdateProgress ID="ManageCategoryUpdateProgress" runat="server" AssociatedUpdatePanelID="ManageCategoryUpdatePanel">
                <ProgressTemplate>
                    <wtp:waitpanel id="ManageCategoryWaitPanel" runat="server" />
                </ProgressTemplate>
            </asp:UpdateProgress>
        </asp:Panel>
        &nbsp;<br />
    </div>
</asp:Content>
